export default [
    {
        id: 1,
        title: "Workout 1:",
        set1: 0.55,
        set2: 0.6,
        set3: 0.65,
        set4: 0.7,
        set5: 0.75,
        set6: 0,
        reps1: 10,
        reps2: 10,
        reps3: 10,
        reps4: 10,
        reps5: 10,
        reps6: 10,
        tips: "This workout should not be too difficult. It is meant to be a warmup for the rest of the program. Focus on form and your other exercises"
    },
    {
        id: 2,
        title: "Workout 2:",
        set1: 0.55,
        set2: 0.6,
        set3: 0.65,
        set4: 0.7,
        set5: 0.75,
        set6: 0.8,
        reps1: 10,
        reps2: 8,
        reps3: 8,
        reps4: 8,
        reps5: 8,
        reps6: 8,
        tips: "Go easy on this workout. It should still be relatively easy. Try focusing on your form and other chest exercises for now."
    },
    {
        id: 3,
        title: "Workout 3:",
        set1: 0.55,
        set2: 0.65,
        set3: 0.7,
        set4: 0.75,
        set5: 0.8,
        set6: 0.85,
        reps1: 10,
        reps2: 8,
        reps3: 6,
        reps4: 6,
        reps5: 6,
        reps6: 6,
        tips: "If you didn't have a spotter on the previous workouts, get one now. This workout should start to become challenging. If you start struggling on the last sets, tell your spotter to help you with the last few reps."
    },
    {
        id: 4,
        title: "Workout 4:",
        set1: 0.55,
        set2: 0.7,
        set3: 0.75,
        set4: 0.8,
        set5: 0.85,
        set6: 0.9,
        reps1: 10,
        reps2: 8,
        reps3: 6,
        reps4: 4,
        reps5: 4,
        reps6: 4,
        tips: "Halfway there! Time to bring some music from now on. The last few sets will be challenging. If you are unable to reach the rep goal, restart the workout another day."
    },
    {
        id: 5,
        title: "Workout 5:",
        set1: 0.55,
        set2: 0.75,
        set3: 0.8,
        set4: 0.85,
        set5: 0.9,
        set6: 0.95,
        reps1: 10,
        reps2: 8,
        reps3: 6,
        reps4: 4,
        reps5: 2,
        reps6: 2,
        tips: "Last Two! This will be a hard one. The last two sets will be very difficult, so come to the gym well rested and fed. If you are unable to reach the rep goal, restart the workout another day."
    },
    {
        id: 6,
        title: "Workout 6:",
        set1: 0.55,
        set2: 0.8,
        set3: 0.85,
        set4: 0.9,
        set5: 0.95,
        set6: 1,
        reps1: 10,
        reps2: 8,
        reps3: 6,
        reps4: 4,
        reps5: 2,
        reps6: 1,
        tips: "Last one! Don't try the workout if you already feel tired. Get a good spotter and go for it! Focus on your form in your last two sets as it is crucial to finish the program."
    },
    
]